### ISSUE TITLE
Code very repetitive

### ISSUE THREAD

**Issue by towerofnix** [TheHockeyist/russian-untransliterator#14]
This particular line gets repeated a whole lot:

```python
cyrillic_string = re.sub("x", "y", cyrillic_string)
```

You could easily simplify a lot of the code by doing this:

```python
def sub(find, replace):
    # Otherwise Python will think we're just defining a new variable
    # in this scope, when really we want to change a global value.
    global cyrillic_string

    cyrillic_string = re.sub(find, replace, cyrillic_string)

# Before:
cyrillic_string = re.sub("a", "а", cyrillic_string)
cyrillic_string = re.sub("b", "б", cyrillic_string)
cyrillic_string = re.sub("c", "ц", cyrillic_string)

# After:
sub("a", "а")
sub("b", "б")
sub("c", "ц")
```

People will discourage you from using global variables, though, and rightfully so, since you *usually* don't want to "pollute" the global namespace (where all global variables are stored).

Plus, with this, you still have to write `sub(x, y)` a bunch of times (it's much shorter, now, of course, but still). Maybe there's a way to make a loop call `sub(x, y)` given some replacement entries instead..? Lists are your friend!

**Comment by TheHockeyist** [comment]
Hmm... it cuts down on text space, but should we make the code more transparent so that we know exactly what it's doing or readable so that others will "understand" it?

I'm not sure. What's the balance between these extremes?

**Comment by towerofnix** [comment]
In my opinion, the balance is often "good function/variable names". Rarely ever do you *really* want to include tons of repetitive code; there's usually a better alternative that's both easier to write and easier to read.

For instance, here, I'd start by doing this:

```python
substitutions = [
    ('a', 'a'),
    ('b', 'б'),
    ('c', 'ц'),
    # ...
]
```

We've got a list of tuples. We already know what lists are, they're just collections of data stored all together in a convenient ordered format. Tuples really only represent pairs of data, so since we're pairing what we're looking for the Latin text to find and the Cyrillic to replace it with, tuples make sense here.

We can use that list like this:

```python
for find, replace in substitutions:
    cyrillic_string = re.sub(find, replace, cyrillic_string)
```

The first line is another `for` loop. It's going to loop through our list of tuples called `substitions`. It'll run the second line (everything in the indented part) for each of the items in the list, storing the values in each tuple in the `find` and `replace` variables.

To read this more simply, in a "human" method:

1. We start by defining a list of pairs of substitutions. (That's clear from the fact that we're using a list of tuples – "pairs" – and storing it in a variable called `substitutions`.)
2. Then we do something for every pair. (It's a standard `for` loop, the kind everyone uses.)
3. That something is replacing every instance of our substitution's "find" with its "replace". (That's pretty clear from our variable names, `find` and `replace`, and the fact that we're modifying a piece of data more than once (from the loop), depending on those find/replace variables which are set by the `for` loop.)

It's not as *verbose* as your piece of code, but I think it actually makes more sense, because of the variable names I used. If I look at your code, I can *guess* that `re.sub` replaces characters, and then apply that to all of those `re.sub` lines, but with what I showed you I don't think you really have to guess anything. (I'm not accounting any of your code comments, if you have any, since I don't think comments are needed in this situation!)

**Comment by TheHockeyist** [comment]
I'll consider it, then.

**Comment by Tymewalk** [comment]
Just implemented. Reopen if there are further issues.
