### ISSUE TITLE
Uh, Houston? We have an unexpected problem!

### ISSUE THREAD

**Issue by TheHockeyist** [TheHockeyist/russian-untransliterator#18]
It's a rather serious one, too.

ети is not a word in Russian. But depending on whether it's eti (эти, these) or yeti (йети, a giant monster from Nepal), it might be fixed incorrectly.

The code initially assumes all Latin e's are Russian е's, and adjusts accordingly. So even a word like йети would be fixed to ети (to remove the j's just in case someone typed нет as njet) before being re-fixed to йети. And эти is initially transliterated as ети to begin with.

As a consequence of this, we don't know if ети was originally eti and needs to be fixed to эти, or if it was yeti or jeti (or even ieti, but I've never seen this one?) and needs to be fixed to йети.

Now, эти is far more common than йети, of course. But the code doesn't know this. Now, there is a Russian game called "Ох уж эти йети". How would it make sure to fix the two ети's differently if it doesn't know any syntax?

**Comment by TheHockeyist** [comment]
Maybe eti - эти and jeti or yeti - йети?

Thoughts?

**Comment by Tymewalk** [comment]
Maybe it could temporarily replace "je" combos with something else, temporarily? For example, `E` since capital letters aren't possible after we make the string lowercase.

Then we just replace `E` with the proper combo.

**Comment by TheHockeyist** [comment]
I think that eventually, we'll need to deal with capital letters.

We could replace "Je/je" with maybe "&/%" or something ridiculous until we figure out the эти/йети problem.

Then we'll need to solve it capitalized.

And in ALL CAPS.

Future development, guys!

**Comment by TheHockeyist** [comment]
Hmmm... any ideas?

**Comment by TheHockeyist** [comment]
Resolved.
