### ISSUE TITLE
You are using variable references instead of strings

### ISSUE THREAD

**Issue by joker314** [TheHockeyist/russian-untransliterator#2]
On line 8, you are using 

```python
str.replace(d, д)
```
wheras the following would be correct

```python
str.replace("d", "д")
```

also, note that on line 4 you are setting `cyrrilic_string` to the function `raw_input` insttead of an empty string (`""`)

Of course, if my code #1 were implemented (which uses a different algorithm) then this will not be a problem

**Comment by TheHockeyist** [comment]
Oops.

**Comment by TheHockeyist** [comment]
Anyways, the Cyrillic string will start as the Latin string and will be replaced Ship of Thesus-style to the correct Russian transliteration.
