### ISSUE TITLE
Vowel combinations.

### ISSUE THREAD

**Issue by TheHockeyist** [TheHockeyist/russian-untransliterator#3]
I added some lines to my code that check for invalid or unlikely letter combinations and replaces them with those that are more likely to occur in the language.

For example, -yy is -ыы, but since the user almost certainly meant -ый, the code corrects this.
And shch is схцх, which is impossible to have in the language, so it first corrects the сх and цх parts to ш and ч, and corrects шч to щ.

I need help with йе and йо. They should be corrected to е and ё always, but some occurrences of йе and йо actually occur in the language, e.g. йогурт, Йемен, район, майор, etc.

**Comment by joker314** [comment]
You could create a dictionary of exceptions, or just clarify what the user meant.

**Comment by TheHockeyist** [comment]
True, but we need to go through the most common cases before asking for clarification.

Йе really only occurs in a few geographical names, like Йемен (Yemen), Йеллоунайф (Yellowknife), and their derivatives. Ие also occurs, like Иерусалим. So a word transliterated with й as i (as sometimes happens) is problematic in this regard - when is i meant to be й and not и?

Not to mention that sometimes a common word like moi can transliterate to мой and мои, equally valid words in Russian.

Generally vowel + i is almost always vowel + й at the end of words or syllables, like мой and хороший, but sometimes, like мои and армии, it's not the case.

In cases like these, clarification or analysis of the grammar may be needed.

**Comment by joker314** [comment]
Oh ok

**Comment by TheHockeyist** [comment]
I added some code correcting йе to е.

Also, corrected ые "ye" to е as well. **Unfortunately, -ые is quite a common grammatical ending and could get messed up.**

Not to mention words like белые might become беле now, or if this is undone, words like kofye incorrectly being transliterated as кофые (adjective) instead of the correct кофе.

I think that the ые thing should only kick in at the beginning of words. This is safe to do since Ы never starts any actual Russian words (aside from foreign names like Ким Чен Ын or the town of Ыб).

**Comment by TheHockeyist** [comment]
What should we do for this issue of ye being both ые and е, both quite common endings? When in doubt, ask the user, of course.

**Comment by joker314** [comment]
Can `ые` be used anywhere but the ends of words?

**Comment by joker314** [comment]
Since they are both valid endings, I think you should just ask the user on what they meant.

**Comment by TheHockeyist** [comment]
We should. When in doubt, ask the user.

E.g. in transliterating the word "kofye", we thought this part of the word was spelled "коф**ые**" in Russian. Is this correct, or is this part spelled "коф**е**"?

**Comment by joker314** [comment]
Is "кофые" a word? We could just have common words that don't follow the rule to check?

**Comment by TheHockeyist** [comment]
кофые is not an actual word. I'm using this as an example.

**Comment by TheHockeyist** [comment]
Also, asking the user could also help in deciding that r**ajo**n should be р**айо**н, but d**ajo**t should be д**аё**т.

**Comment by TheHockeyist** [comment]
Йемен and Йеллоунайф work now.

**Comment by TheHockeyist** [comment]
The program now determines when йо should be used at the start of a word instead of ё. This happens to cover most й cases at the start of words.

**Comment by TheHockeyist** [comment]
Added some cases where йе is used instead of е to cover more words that start with й.

**Comment by TheHockeyist** [comment]
Yes, I went through the Russian Wikipedia for articles that started with йе or йо, and selected some of the more common words and combinations that I saw.

**Comment by TheHockeyist** [comment]
Most of the common -йо- words should render correctly now.

**Comment by TheHockeyist** [comment]
I'd say we're done with this now, as most of the issues here have been made into their own topics.
