### ISSUE TITLE
The letters ъ and ь.

### ISSUE THREAD

**Issue by TheHockeyist** [TheHockeyist/russian-untransliterator#4]
They are transliterated as " and ' respectively. For some reason, it doesn't work and does weird things to the code.

Any fixes?

**Comment by joker314** [comment]
You have done `"""` but that is interpreted as `""` then an unclosed `"`.

To fix, you must escape the inner `"` with a backslash: `"\""`, or use single quotes.

**Comment by TheHockeyist** [comment]
Done.

**Comment by joker314** [comment]
@TheHockeyist Note that you don't need to escape the apostrophe since it is in double quotes.
