### ISSUE TITLE
Э in Russian words.

### ISSUE THREAD

**Issue by TheHockeyist** [TheHockeyist/russian-untransliterator#5]
e always goes to е in the current code, but some Russian words have э instead. Thankfully э is very rare, but it does occur in some common words like это and its derivatives (by far the most common use of it), электричество, эрбий, and sometimes after a vowel like поэт and аэропорт.

Also, some words switch between е and э, e.g. хетчбек/хэтчбек.

Proper names are also an issue, e.g. Мао Цзэдун, even though according to the orthographical rules, it should be Мао Цзедун, which is incorrect. It's really Мао Цзэдун.

We need some way to work on this issue.

**Comment by joker314** [comment]
Asking for user clarification, and mapping `eto[...]` to `это[...]`

**Comment by TheHockeyist** [comment]
Э is a rare letter, and thankfully we can probably get away with just making a list of all the major words with э and seeing if any of the words match the uncorrected versions with е.

E.g. if the code sees ето, correct it to это, and if it sees аеро-, a prefix, correct it to аэро-.

If the word might still be incorrect, ask the user for clarification.

**Comment by joker314** [comment]
You might also want to map `je` to `э` or something similar.

**Comment by TheHockeyist** [comment]
je is already a standard for е.

**Comment by Tymewalk** [comment]
Maybe we could reduce the cases where `e` becomes `э` down to a few?

i.e, `-оeт` always becomes `-оэт`.

**Comment by TheHockeyist** [comment]
-оет is used in some verb conjugations, though.

**Comment by TheHockeyist** [comment]
Not to mention that the spellings of some words (especially recent words) are inconsistent, see my хетчбек/хэтчбек example above.

**Comment by TheHockeyist** [comment]
Corrected the most common э issue - это. May need some context to determine whether the string "ето" is это, этот, этом, etc. or where it's part of another word, like лето.

**Comment by TheHockeyist** [comment]
Added a few examples.

**Comment by TheHockeyist** [comment]
One thing:

It will never be э after the letters ь and ъ. Those combinations just never happen. If we transliterate and get подъэзд by accident, we should realize that the correct word is подъезд.

**Comment by TheHockeyist** [comment]
Ongoing effort to write э in words.

**Comment by Tymewalk** [comment]
@TheHockeyist On it. I'll add that rule in now.

**Comment by TheHockeyist** [comment]
No prob. ;-).

We're still continuing on.

**Comment by TheHockeyist** [comment]
I think we're mostly done with this.
